server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    # Usa las variables que ya tienes en docker-compose (POSTGRES_* y DB_HOST/DB_PORT)
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # Deshabilitar para que solo Flyway maneje el esquema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200}"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true


jwt:
  alg: ${JWT_ALG:HS256}
  secret: ${JWT_SECRET:}              # ← SIN fallback corto ni typos (NO `${JWT SECRET}`)
  accessTtlMinutes: ${ACCESS_TTL_MINUTES:15}
  sessionTtlDays: ${SESSION_TTL_DAYS:60}

refresh:
  hmacSecret: ${REFRESH_HMAC_SECRET:}



cookies:
  secure: ${COOKIE_SECURE:false}
  sameSite: ${COOKIE_SAMESITE:Strict}
  domain: ${COOKIE_DOMAIN:}
  path: ${COOKIE_PATH:/}

epayco:
  base-url: ${EPAYCO_BASE_URL:https://apify.epayco.co}
  public-key: ${EPAYCO_PUBLIC_KEY:?EPAYCO_PUBLIC_KEY is required}
  private-key: ${EPAYCO_PRIVATE_KEY:?EPAYCO_PRIVATE_KEY is required}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none           # none | list | full
    default-model-expand-depth: 0 # no expandir modelos por defecto
    default-models-expand-depth: 0
  api-docs:
    path: /v3/api-docs

# Configuración de Logging
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.academia.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/academy-landing-platform.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
