server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    # Usa las variables que ya tienes en docker-compose (POSTGRES_* y DB_HOST/DB_PORT)
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update        # crea/actualiza tablas si no existen (útil para arrancar)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

app:
  corsAllowed: ${CORS_ALLOWED_ORIGINS:} # coma-separado

jwt:
  alg: ${JWT_ALG:HS256}
  secret: ${JWT_SECRET:super-secret-jwt-key-minimum-256-bits-required-change-in-production}
  privateKey: ${JWT_PRIVATE_KEY:}
  publicKey: ${JWT_PUBLIC_KEY:}
  accessTtlMinutes: ${ACCESS_TTL_MINUTES:15}
  sessionTtlDays: ${SESSION_TTL_DAYS:60}

refresh:
  hmacSecret: ${REFRESH_HMAC_SECRET:super-secret-refresh-hmac-key-minimum-256-bits-change-in-production}

cookies:
  secure: ${COOKIE_SECURE:false}
  sameSite: ${COOKIE_SAMESITE:Strict}
  domain: ${COOKIE_DOMAIN:}
  path: ${COOKIE_PATH:/}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
