server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${POSTGRES_DB:appdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate   # usamos Flyway
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  corsAllowed: ${CORS_ALLOWED_ORIGINS:}  # coma-separado

jwt:
  alg: ${JWT_ALG:HS256}
  secret: ${JWT_SECRET:dev-secret-change-me}
  privateKey: ${JWT_PRIVATE_KEY:}
  publicKey: ${JWT_PUBLIC_KEY:}
  accessTtlMinutes: ${ACCESS_TTL_MINUTES:15}
  sessionTtlDays: ${SESSION_TTL_DAYS:60}

refresh:
  hmacSecret: ${REFRESH_HMAC_SECRET:dev-rt-hmac}

cookies:
  secure: ${COOKIE_SECURE:false}
  sameSite: ${COOKIE_SAMESITE:Strict}
  domain: ${COOKIE_DOMAIN:}
  path: ${COOKIE_PATH:/}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
