
CREATE TABLE IF NOT EXISTS countries (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    phone_code VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS states (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country_id BIGINT NOT NULL REFERENCES countries(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cities (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    state_id BIGINT NOT NULL REFERENCES states(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_states_country_id ON states(country_id);
CREATE INDEX IF NOT EXISTS idx_cities_state_id ON cities(state_id);

ALTER TABLE countries ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS countries_id_seq;

ALTER TABLE states ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS states_id_seq;

ALTER TABLE cities ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS cities_id_seq;

